### ISSUE TITLE
Node version incompatibilities?

### ISSUE THREAD

**Issue by mikecann** [chodorowicz/ts-debounce#14]
Hey, 

We are getting this issue on our CI when trying to `yarn install` with ts-debounce: 

```
error ts-debounce@0.3.2: The engine "node" is incompatible with this module. Expected version ">=8.*". Got "6.14.4"
```

Any idea?

**Comment by mikecann** [comment]
Actually we probably want to be running node 8, we will change the server.

**Comment by chodorowicz** [comment]
Actually keeping such a high Node dependency doesn't make sense to be hones. I've removed it for now. 
https://github.com/chodorowicz/ts-debounce/pull/15/commits/d3fce3c5a650755f71702909ec17396cacd6556ec
But using newer version of Node is a good idea anyway :)

Greetings!

**Comment by mikecann** [comment]
Oh awesome, thanks! Yes indeed, both are good moves, thanks!
