### ISSUE TITLE
How can i cancel my debounce.

### ISSUE THREAD

**Issue by sushanthdornala** [chodorowicz/ts-debounce#26]
As a developer am using debounce function on filters.If i want to redirect to another page i want to cancel all the significant calls of debounce.

**Comment by st-currenxie** [comment]
Any updates on this issue ?

**Comment by chodorowicz** [comment]
Hey @sushanthdornala and @st-currenxie! Sorry for very late response.
I've just released a new version `2.1.0` which possibility to cancel debounced function. Let me know if that suits your needs.

https://github.com/chodorowicz/ts-debounce#cancellation
