### ISSUE TITLE
Same debounce function in multiple React components

### ISSUE THREAD

**Issue by flashtheman** [chodorowicz/ts-debounce#48]
I've noticed a very odd behaviour. I have different intances of react components (with different unique ids/keys) and these components/instances call the debounce function via a 'scroll' event listener. Maybe it's important to mention that the react components add the same event listener to the same (EXTERNAL = not within the react component) div element.
The problem is that when I scroll through the document, all of the react components/instances get the scroll event but ONLY ONE component/instances gets into the debounce function. This is difficult to debug for me but it seems that the react components share the same debounce function which I don't want.

Is this possible? And if yes, can I somehow make it so each react component instance has its own debounce function?

**Comment by chodorowicz** [comment]
It must something React specific. You'd need to create a minimal reproducible example of this problem e.g. on [CodeSandbox](http://codesandbox.io) so that other could take a look into it.
